### ISSUE TITLE
<picture> support?

### ISSUE THREAD

**Issue by vasfvitor** [MarketingPipeline/CSS-Image-Loader#5]
From https://www.w3schools.com/tags/tag_picture.asp
```
<picture>
  <source media="(min-width:650px)" srcset="img_pink_flowers.jpg">
  <source media="(min-width:465px)" srcset="img_white_flower.jpg">
  <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture>
```
Do you think it's necessary to specify <picture> in this project?

**Comment by MarketingPip** [comment]
> From https://www.w3schools.com/tags/tag_picture.asp
> 
> ```
> <picture>
>   <source media="(min-width:650px)" srcset="img_pink_flowers.jpg">
>   <source media="(min-width:465px)" srcset="img_white_flower.jpg">
>   <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
> </picture>
> ```
> 
> Do you think it's necessary to specify in this project?

Sorry for the late reply @vasfvitor I love the incentive to improve this project. Tho - this is supposed to be an example without providing an extra HTML tag. 

I was thinking about adding an option for using a div < as before works on webkits for divs but not the img tag. But figured it would go against the purpose of not adding an extra HTML tag so opted not too. 

If you can find anyway to find a work around for the before issue on webkit tho using only img tag. Feel free to make a PR / issue / suggestion etc. :+1:  

ps; hope all is well! :smiley:
